<?php

return [
    'charge' => [
        'monthly' => [
            "👋 Olá, :name!\n😊 Esperamos que você esteja bem.\n\n💝 Sua contribuição para o Projeto Social Solidificando Vidas, referente ao mês de :month, já está disponível. Abaixo, você encontra o boleto para pagamento.\n\n💪 Seu apoio é fundamental para que nosso trabalho continue alcançando e transformando vidas. Agradecemos imensamente sua generosidade.\n\n🙏 Deus te abençoe! Gratidão. ✨ \n\n :link",
            "👋 Olá, Parceiro Contribuinte :name!\n😄 Tudo bem?\n\n📋 Estamos enviando o boleto referente à sua contribuição do mês de :month para o Projeto Social Solidificando Vidas. Sua solidariedade e compromisso fazem toda a diferença! 💙\n\n🙏 Muito obrigado por sua generosidade.\n\n✨ Deus abençoe! Gratidão. \n\n :link",
            "👋 E aí, :name!\n🚀 Sua contribuição mensal é a força motriz do Projeto Social Solidificando Vidas!\n\n📄 Segue o boleto para pagamento referente ao mês de :month. Sua ajuda nos permite continuar levando esperança e apoio a quem mais precisa. 🌟\n\n❤️ Agradecemos de coração!\n\n🙏 Deus te abençoe! ✨ \n\n :link",
            "🎩 Prezado(a) :name,\n💼 Sua contribuição para o Projeto Social Solidificando Vidas, referente ao mês de :month, já pode ser paga. O boleto está anexado abaixo.\n\n🏛️ Sua participação é um pilar essencial para o sucesso das nossas ações. Muito obrigado por ser um agente de transformação! 🌟\n\n🙏 Que Deus te abençoe ricamente!\n\n✨ Gratidão! \n\n :link",
            "👋 Olá, :name!\n🤗 Obrigado por fazer parte do Projeto Social Solidificando Vidas!\n\n📋 Anexamos o boleto para sua contribuição do mês de :month, conforme nosso acordo.\n\n💡 Sua generosidade nos inspira. Cada doação é um passo em direção a um futuro melhor para muitas famílias. 🌈\n\n🙏 Gratidão! Deus te abençoe! ✨ \n\n :link",
            "👋 Olá, :name!\n⏰ Passando para lembrar que já está disponível o boleto referente à sua contribuição do mês de :month para o Projeto Social Solidificando Vidas.\n\n🤝 Sua parceria é muito importante para nós e para todos que são beneficiados pelo projeto.\n\n💙 Muito obrigado por sua sensibilidade e apoio.\n\n🙏 Deus te abençoe! ✨ \n\n :link",
            "👋 Olá, Parceiro(a) :name!\n📋 Segue o boleto para o pagamento da sua contribuição mensal de :month, destinada ao Projeto Social Solidificando Vidas.\n\n🌟 Seu apoio contínuo é uma bênção para nossa comunidade. Não há palavras para expressar nossa gratidão.\n\n🙏 Que Deus te recompense!\n\n✨ Gratidão! \n\n :link",
            "👋 Prezado(a), :name!\n💪 Sua colaboração é o que torna o Projeto Social Solidificando Vidas possível.\n\n📋 Anexamos o boleto para sua contribuição de :month.\n\n🌍 Com a sua ajuda, estamos construindo um mundo mais justo e solidário.\n\n🙏 Muito obrigado! Deus te abençoe! ✨ \n\n :link",
            "👋 Olá, :name!\n Receba o nosso carinho e gratidão!\n\n📋 Sua contribuição para o mês de :month, do Projeto Social Solidificando Vidas, já está disponível. O boleto para pagamento está logo abaixo.\n\n❤️ Seu gesto de amor e generosidade é fundamental para o nosso trabalho.\n\n🙏 Deus abençoe sua vida!\n\n✨ Gratidão! \n\n :link",
            "🎩 Prezado(a) :name,\n🗝️ Você é a peça-chave para o sucesso do Projeto Social Solidificando Vidas!\n\n📋 Em anexo, você encontra o boleto referente à sua contribuição do mês de :month, conforme o termo de adesão.\n\n🌟 Sua ajuda transforma vidas e espalha esperança. Muito obrigado por fazer a diferença.\n\n🙏 Deus te abençoe grandemente!\n\n✨ Gratidão!"
        ],
        'single' => [
            "👋 Olá, :name! 😊\nChegou o boleto da sua contribuição para o Projeto Social Solidyficando Vidas. Sua generosidade faz a diferença!\n\n🙏 Desde já, nosso muito obrigado. 💖 \n\n :link",
            "👋 E aí, :name!\nAgradecemos muito sua parceria. O boleto da sua contribuição mensal para o Solidyficando Vidas já está disponível. Juntos, transformamos vidas!\n\n✨ Gratidão! 🙌 \n\n :link",
            "👋 Oi, :name!\nJá está com a gente o boleto da sua contribuição para o Projeto Solidyficando Vidas. Sua ajuda é fundamental para quem mais precisa.\n\n❤️ Obrigado por ser nosso parceiro! 🤝\n\n🙏 Deus te abençoe! \n\n :link",
            "👋 Olá, :name, nosso Contribuinte Parceiro! 🌟\nEnvie para pagamento o boleto da sua doação, conforme nosso termo de adesão. Sua sensibilidade nos ajuda a levar esperança.\n\n✨ Gratidão! 🙏 \n\n :link",
            "👋 Olá, :name! 😊\nSua contribuição para o Projeto Solidyficando Vidas já pode ser paga. Juntos, construímos um futuro melhor! 🏡\n\nObrigado pela sua generosidade.\n\n❤️ Deus te abençoe! 🙏 \n\n :link",
            "👋 Oi, :name!\nEstamos enviando o boleto da sua contribuição ao Projeto Solidyficando Vidas. Sua parceria é um presente para muitas famílias. 🎁\n\n🙏 Muito obrigado! \n\n :link",
            "👋 Olá, :name! 😊\nSeu boleto de contribuição para o Projeto Social Solidyficando Vidas já está disponível. Sua ajuda é a força que move o nosso projeto. 💪\n\n❤️ Gratidão pela sua generosidade! \n\n :link",
            "👋 E aí, :name! 🥳\nPassando para lembrar sobre a sua contribuição ao Solidyficando Vidas! O boleto já está aqui. Seu apoio é essencial! 🚀\n\n🙏 Muito obrigado por nos ajudar a fazer o bem. \n\n :link",
            "👋 Olá, :name! ✨\nConforme nosso acordo, o boleto da sua contribuição para o Projeto Solidyficando Vidas já foi gerado. Sua doação é uma semente de esperança. 🌻\n\n🙏 Deus te abençoe e multiplique! \n\n :link",
            "👋 Oi, :name! 💖\nSeu apoio ao Projeto Solidyficando Vidas é muito importante! O boleto da sua contribuição já está disponível para pagamento. Obrigado por nos ajudar a mudar o mundo. 🌎\n\n🙏 Gratidão! \n\n :link"
        ],
    ],
];
